import React, { useState } from 'react';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { Download, Loader2, FileText, CheckCircle, ShieldCheck, X } from 'lucide-react';

export default function ExportPanel({ companyData }) {
    const [isGenerating, setIsGenerating] = useState(false);
    const [showPreview, setShowPreview] = useState(false);

    // Map actual incoming AI data to the format the PDF requires, falling back to mock if empty
    const data = companyData ? {
        cmp: companyData.name || "Unknown Entity",
        credit_score: companyData.credit_score || 0,
        risk_grade: companyData.risk_grade || "N/A",
        metrics: companyData.financials ? [
            { label: "Revenue", value: companyData.financials.revenue || "N/A" },
            { label: "EBITDA Margin", value: companyData.financials.ebitda_margin || "N/A" },
            { label: "Debt/Equity", value: companyData.financials.debt_equity || "N/A" },
            { label: "Current Ratio", value: companyData.financials.current_ratio || "N/A" }
        ] : [],
        top_flags: companyData.india_risk?.sector_flags || companyData.shap_values?.map(s => s.feature) || [],
        recommendation: companyData.risk_grade === "AAA" || companyData.risk_grade === "AA" 
            ? "Approved for maximum limit extension. Maintain standard covenants."
            : companyData.risk_grade === "BBB"
            ? "Conditionally Approved. Recommend elevated pricing and strict promoter guarantees."
            : "REJECTED. Breach of systemic risk thresholds. Do not onboard."
    } : {
        cmp: "Tata Steel Ltd",
        credit_score: 810,
        risk_grade: "AAA",
        metrics: [
            { label: "Revenue", value: "₹1,40,000 Cr" },
            { label: "EBITDA Margin", value: "22.5%" },
            { label: "Debt/Equity", value: "0.8x" },
            { label: "Current Ratio", value: "1.4x" }
        ],
        top_flags: [
            "Strong operating cash flows covering debt obligations > 4x.",
            "Global steel overcapacity risks mitigated by domestic infra push.",
            "Consistent tracking of environmental compliance."
        ],
        recommendation: "Approved for maximum limit extension. Maintain standard covenants."
    };

    const generatePDF = async () => {
        setIsGenerating(true);
        try {
            // Target the actual preview DOM element to capture it
            const element = document.getElementById('pdf-preview-content');
            
            // Generate highest quality canvas
            const canvas = await html2canvas(element, { 
                scale: 2,
                backgroundColor: '#ffffff',
                useCORS: true
            });
            
            const imgData = canvas.toDataURL('image/png');
            
            // Standard A4 dimensions
            const pdf = new jsPDF({
                orientation: 'portrait',
                unit: 'mm',
                format: 'a4'
            });
            
            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
            
            pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
            
            // Add Intelli-Credit digital watermark
            pdf.setTextColor(150, 150, 150);
            pdf.setFontSize(10);
            pdf.text(`Generated by Intelli-Credit AI Engine | ${new Date().toLocaleDateString()}`, 10, 285);
            
            pdf.save(`IntelliCredit_CAM_${data.cmp.replace(/\s+/g, '_')}.pdf`);
        } catch (error) {
            console.error("PDF Generation failed:", error);
        } finally {
            setIsGenerating(false);
            setShowPreview(false);
        }
    };

    return (
        <div className="bg-[#0A0A0F] border border-slate-800 p-6 rounded-2xl w-full text-slate-200">
            <div className="flex flex-col md:flex-row justify-between items-center gap-6">
                <div>
                    <h2 className="text-xl font-bold text-white flex items-center gap-2">
                        <FileText className="text-[#4FC3F7]" /> Executive Credit Appraisal Memo
                    </h2>
                    <p className="text-sm text-slate-400 mt-1">Export a beautifully formatted, bank-ready PDF dossier containing all AI logic, SHAP values, and risk scores.</p>
                </div>
                
                <button 
                    onClick={() => setShowPreview(true)}
                    className="px-8 py-4 bg-gradient-to-r from-[#00FF87] to-[#00b35f] text-black rounded-xl font-bold flex items-center gap-3 hover:scale-105 transition-transform shadow-[0_0_20px_rgba(0,255,135,0.4)] whitespace-nowrap"
                >
                    <Download size={20} /> Preview & Export PDF
                </button>
            </div>

            {/* PREVIEW MODAL */}
            {showPreview && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-in fade-in duration-300">
                    <div className="bg-[#1E293B] rounded-2xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden shadow-2xl shadow-black border border-slate-700">
                        
                        <div className="p-4 border-b border-slate-700 flex justify-between items-center bg-[#0B1426]">
                            <h3 className="font-bold text-white flex items-center gap-2">
                                <FileText className="text-[#00FF87]" /> Report Preview
                            </h3>
                            <button onClick={() => setShowPreview(false)} className="text-slate-400 hover:text-white transition-colors">
                                <X size={24} />
                            </button>
                        </div>

                        {/* THIS CONTAINER IS WHAT GETS PRINTED TO THE PDF */}
                        <div className="flex-1 overflow-y-auto bg-slate-200 p-8 custom-scrollbar relative">
                            <div 
                                id="pdf-preview-content" 
                                className="bg-white text-slate-900 p-10 shadow-2xl mx-auto w-full max-w-[210mm] min-h-[297mm]" 
                            >
                                {/* Header */}
                                <div className="flex justify-between items-end border-b-4 border-slate-900 pb-6 mb-8">
                                    <div>
                                        <h1 className="text-4xl font-black font-serif tracking-tight text-slate-900">Intelli-Credit<span className="text-amber-500">.</span></h1>
                                        <p className="text-sm font-mono mt-1 text-slate-500 font-bold uppercase tracking-widest">Automated Credit Appraisal Memo</p>
                                    </div>
                                    <div className="text-right">
                                        <p className="text-sm font-bold">Date: {new Date().toLocaleDateString()}</p>
                                        <p className="text-sm font-bold text-slate-500 font-mono">Ref: IC-CAM-{Math.floor(Math.random() * 90000) + 10000}</p>
                                    </div>
                                </div>

                                {/* Company Title & Grade */}
                                <div className="flex justify-between items-center mb-10 bg-slate-50 p-6 rounded-xl border border-slate-200">
                                    <div>
                                        <h2 className="text-3xl font-black text-slate-800">{data.cmp}</h2>
                                        <p className="text-slate-500 font-medium flex items-center gap-2 mt-1">
                                            <ShieldCheck size={16} className="text-emerald-500" /> Verified by AI Extractor
                                        </p>
                                    </div>
                                    <div className="text-right">
                                        <p className="text-xs uppercase tracking-widest font-bold text-slate-400 mb-1">Final AI Rating</p>
                                        <div className="flex items-center gap-4">
                                            <span className="text-5xl font-black text-slate-900">{data.credit_score}</span>
                                            <span className={`px-4 py-2 text-2xl font-bold uppercase rounded border-2 ${data.risk_grade.includes('A') || data.risk_grade === 'BBB' ? 'bg-emerald-100 text-emerald-700 border-emerald-300' : 'bg-rose-100 text-rose-700 border-rose-300'}`}>
                                                {data.risk_grade}
                                            </span>
                                        </div>
                                    </div>
                                </div>

                                {/* Metrics Summary */}
                                <h3 className="text-lg font-bold uppercase tracking-widest text-slate-800 border-b-2 border-slate-200 pb-2 mb-4">Core Financial Metrics</h3>
                                <div className="grid grid-cols-4 gap-4 mb-10">
                                    {data.metrics.map((m, i) => (
                                        <div key={i} className="p-4 border border-slate-200 rounded-lg">
                                            <p className="text-xs text-slate-500 uppercase font-bold mb-1">{m.label}</p>
                                            <p className="text-xl font-black text-slate-800">{m.value}</p>
                                        </div>
                                    ))}
                                </div>

                                {/* Key Insights */}
                                <h3 className="text-lg font-bold uppercase tracking-widest text-slate-800 border-b-2 border-slate-200 pb-2 mb-4">AI Derived Risk Vectors</h3>
                                <div className="space-y-4 mb-10">
                                    {data.top_flags.map((flag, i) => (
                                        <div key={i} className="flex gap-4 p-4 bg-slate-50 rounded-lg border border-slate-100 shadow-sm">
                                            <div className="mt-1 flex-shrink-0">
                                                <CheckCircle className="text-emerald-500 w-5 h-5" />
                                            </div>
                                            <p className="text-slate-700 font-medium leading-relaxed">{flag}</p>
                                        </div>
                                    ))}
                                </div>

                                {/* Final Recommendation */}
                                <div className="bg-slate-900 text-white p-6 rounded-xl relative overflow-hidden">
                                    <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500 rounded-full blur-[50px] opacity-20 transform translate-x-10 -translate-y-10"></div>
                                    <h3 className="text-xs text-indigo-300 uppercase tracking-widest font-bold mb-3">System Recommendation</h3>
                                    <p className="text-lg font-medium leading-relaxed">
                                        {data.recommendation}
                                    </p>
                                </div>
                                
                                {/* Footer Watermark */}
                                <div className="mt-20 pt-6 border-t border-slate-200 text-center">
                                    <p className="text-xs text-slate-400 font-medium">
                                        This document was generated automatically by the Intelli-Credit ML Engine. 
                                        Calculations are deterministic based on provided documentation.
                                    </p>
                                </div>
                            </div>
                        </div>

                        {/* Export Actions Pane */}
                        <div className="p-4 bg-[#0B1426] border-t border-slate-700 flex justify-end">
                            <button 
                                onClick={generatePDF}
                                disabled={isGenerating}
                                className="px-8 py-3 bg-[#00FF87] hover:bg-[#00e67a] text-black rounded-lg font-bold flex items-center gap-2 transition-all disabled:opacity-50 min-w-[200px] justify-center"
                            >
                                {isGenerating ? (
                                    <><Loader2 className="animate-spin" /> Rendering PDF...</>
                                ) : (
                                    <><Download size={18} /> Download HD PDF</>
                                )}
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
